# Generated by Django 4.1 on 2024-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(0, 'Question'), (1, 'Test'), (2, 'AI')], default=0)),
            ],
        ),
    ]
