# Generated by Django 4.1 on 2024-09-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.IntegerField(choices=[(0, 'Question'), (1, 'Test'), (2, 'AI'), (3, 'Hint'), (4, 'Note')], default=0),
        ),
    ]
