# Generated by Django 4.1 on 2025-11-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('platform', models.CharField(choices=[('TG', 'Telegram'), ('BALE', 'Bale')], default='BALE', max_length=10)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField(null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_student', models.BooleanField(default=1)),
                ('state', models.IntegerField(default=0)),
                ('calculated_score', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.grade')),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to='user.user')),
            ],
            options={
                'unique_together': {('platform', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserQuestionRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_questions', to='user.user')),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
