# Generated by Django 4.1 on 2024-07-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
