# Generated by Django 4.1 on 2024-07-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userquestionrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionrel',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
