# Generated by Django 4.1 on 2024-08-15 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_calculated_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 15, 4, 54, 21, 750076)),
        ),
    ]
