# Generated by Django 4.1 on 2024-08-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_inviter_alter_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.CharField(choices=[('TG', 'Telegram'), ('BALE', 'Bale')], default='BALE', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('platform', 'user_id')},
        ),
    ]
