# Generated by Django 4.1 on 2024-08-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_platform_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='platform',
        ),
    ]
