# Generated by Django 4.1 on 2024-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_unique_together_remove_user_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
