# Generated by Django 4.1 on 2024-08-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
