# Generated by Django 4.1 on 2024-08-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='backup',
            new_name='user_id',
        ),
    ]
