# Generated by Django 4.1 on 2024-08-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_backup_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='us',
        ),
    ]
