# Generated by Django 4.1 on 2024-08-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_rename_user_id_user_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
