# Generated by Django 4.1 on 2024-08-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='us',
        ),
    ]
