# Generated by Django 4.1 on 2024-08-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_user_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.CharField(choices=[('TG', 'Telegram'), ('BALE', 'Bale')], default='BALE', max_length=10),
        ),
    ]
