# Generated by Django 4.1 on 2024-08-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
