# Generated by Django 4.1 on 2024-08-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
