# Generated by Django 4.1 on 2024-08-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('platform', 'user_id')},
        ),
    ]
