# Generated by Django 4.1 on 2024-07-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade_number', models.IntegerField()),
                ('grades', models.ManyToManyField(to='content.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField(null=True)),
                ('class_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.class')),
            ],
        ),
    ]
