# Generated by Django 4.1 on 2025-11-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepackage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='user.user'),
        ),
        migrations.AddField(
            model_name='notepackage',
            name='class_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='content.class'),
        ),
        migrations.AddField(
            model_name='notepackage',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvotes', to='user.user'),
        ),
        migrations.AddField(
            model_name='notepackage',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvotes', to='user.user'),
        ),
        migrations.AddField(
            model_name='class',
            name='grades',
            field=models.ManyToManyField(related_name='classes', to='content.grade'),
        ),
    ]
