# Generated by Django 4.1 on 2024-09-08 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_user_last_name'),
        ('content', '0006_notepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepackage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='user.user'),
        ),
    ]
