# Generated by Django 4.1 on 2024-09-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_user_last_name'),
        ('content', '0008_alter_notepackage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepackage',
            name='downvote',
            field=models.ManyToManyField(related_name='downvote', to='user.user'),
        ),
        migrations.AddField(
            model_name='notepackage',
            name='upvote',
            field=models.ManyToManyField(related_name='upvotes', to='user.user'),
        ),
    ]
