# Generated by Django 4.1 on 2024-09-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_user_last_name'),
        ('content', '0009_notepackage_downvote_notepackage_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepackage',
            name='downvote',
            field=models.ManyToManyField(related_name='downvotes', to='user.user'),
        ),
    ]
