# Generated by Django 4.1 on 2024-09-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_notepackage_downvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notepackage',
            old_name='downvote',
            new_name='downvotes',
        ),
        migrations.RenameField(
            model_name='notepackage',
            old_name='upvote',
            new_name='upvotes',
        ),
    ]
